#!/bin/bash

set -eux

docker build . --pull --build-arg BASE_IMAGE=php:$DOCKER_TAG-alpine -f $DOCKERFILE_PATH -t $IMAGE_NAME

docker run --rm $IMAGE_NAME -d zend_extension=xdebug.so -d opcache.enable_cli=1 /usr/local/bin/docker-php-check.php
