name: CI
env:
  DOCKERHUB_USERNAME: ngyuki
  LATEST_VERSION: 8.1
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - run: make -B ${{ matrix.php-version }}/Dockerfile

      - run: make ${{ matrix.php-version }}

      - run: make ${{ matrix.php-version }}/test

      - if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          make ${{ matrix.php-version }}/push
          if [ "${{ matrix.php-version }}" == "$(make echo-latest)" ]; then
            make latest
            make latest/push
          fi
