name: CI
env:
  DOCKER_REPO: ngyuki/php-dev
  LATEST_VERSION: 8.1
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - run: |
          version="${{ matrix.php-version }}"
          if [ "$version" == "$LATEST_VERSION" ]; then
            echo "DOCKER_TAGS=$version,latest" >> $GITHUB_ENV
          else
            echo "DOCKER_TAGS=$version" >> $GITHUB_ENV
          fi

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.php-version }}/Dockerfile
          push: false
          tags: ${{ env.DOCKER_TAGS }}
